export const LOAD_GEO = 'LOAD_GEO' 
export const ADD_ZONE = 'ADD_ZONE'
export const FORMAT_GEO = 'FORMAT_GEO'
export const IS_DRAWING_STATUS = 'IS_DRAWING_STATUS'
export const SELECTED_ZONE = 'SELECTED_ZONE' 
export const UNSELECTED_ZONE = 'UNSELECTED_ZONE'
